### ISSUE TITLE
Latest version not published to Galaxy

### ISSUE THREAD

**Issue by tigattack** [prometheus-community/ansible#164]
Looks like 0.5.2 was never tagged, so the release workflow didn't run for 126e68edadd3cff8da42a7730060c9cabdd8e213.

![image](https://github.com/prometheus-community/ansible/assets/10629864/ddc5e9df-1fc4-41e0-a723-d5486cb2e831)

**Comment by ansonhoyt** [comment]
Same for `0.6.0`.

**Comment by gardar** [comment]
This is expected, the version number is bumped on the main branch before the release is published.

**Comment by ansonhoyt** [comment]
Thanks for explaining Garðar! Since the [galaxy listing](https://galaxy.ansible.com/prometheus/prometheus) lagged behind the repo (and [the docs](https://prometheus-community.github.io/ansible)) by two releases, it looked like something might be broken. I'm pretty ignorant about what is normal for Galaxy, but it might be worth a mention in the docs. 😅 

I've just "followed" the collection on Galaxy to get notified when it is published.

**Comment by gardar** [comment]
Yeah it's perhaps not ideal that we bump the version and write the changelog on the main branch before actually making the release on github and galaxy... But to change that we would need to make the CI even more complex than it is which is why I thought it would be ok to have it like this, might need to re-evaluate that if it's confusing everyone.

**Comment by nlamirault** [comment]
Same for `0.7.0`
